### ISSUE TITLE
Stop/Start cluster "machines" to allow persistent environments

### ISSUE THREAD

**Issue by carlosedp** [weaveworks/footloose#106]
Footloose should have a command to stop the "machines" persisting it's state that's in the container to allow another "machine" to be started using same ports.

Apparently, each container is created with `--rm`as seen in the parameter `"AutoRemove": true,` in `docker inspect`.

For example I use it to have different versions of a OpenShift cluster and each exposes the same ports. I'd like to keep the containers for the different versions for testing just doing a "footloose start/stop" on each config.

**Comment by carlosedp** [comment]
Addressing this with PR #107.

**Comment by dlespiau** [comment]
This is closed by #107. Thanks a lot for your contribution! makes a difference :)
