### ISSUE TITLE
show: machine should be named with the hostname, not the container name

### ISSUE THREAD

**Issue by dlespiau** [weaveworks/footloose#109]
To be consistent with the rest of the interface (ie. ssh) we should only use the name (hostname) of the node when specifying it on the command line:

```
$ footloose show node0
```
not
```
$ footloose show cluster-node0
```

**Comment by Skarlso** [comment]
The problem with that is, that hostname is computed. And if the container is not running, you won't be able to list it. This way, you can list it even in stopped state. And considering that now containers persist, I would think your first instinct would be to use a name. What do you think?

**Comment by Skarlso** [comment]
I stand corrected. I wasn't certain, so I checked. I'm displaying hostname even in stopped state. :)
