### ISSUE TITLE
Use a more selective docker ps command in tests

### ISSUE THREAD

**Issue by dlespiau** [weaveworks/footloose#145]
At the moment, when a test fails, the containers that they created stay around. Other tests may try to inspect the list of docker containers and fail because there are more containers than they expect;

https://travis-ci.org/weaveworks/footloose/builds/520829318?utm_source=github_status&utm_medium=notification

Instead of using `%out docker ps --format {{.Names}}` we need to only select the containers that have been created by the test inspecting the list of containers. We can use the labels we now set on containers for that.

**Comment by najeal** [comment]
I will take a look
