### ISSUE TITLE
Create docker network for containers?

### ISSUE THREAD

**Issue by wintamute** [weaveworks/footloose#158]
Currently when creating multiple nodes, it's not possible to use container names for communicating between the nodes since the containers are attached to the default network of Docker.
My use case usually is testing stuff which requires that containers can talk to each other without having to specify the IP first.
Being Docker containers, you cannot modify /etc/hosts directly (for example via ansible), but can specify additional hosts on the command line which will then get added to the containers hosts file.
docker-compose creates a separate network for each environment which enables DNS with container names, so using the container name for network connections just works.

Does it make sense to do something similar in footloose? Creating a network when creating the cluster and deleting it again when the cluster gets deleted?
Or modify the container creation args to add all nodes?

I'd be willing to do the implementation, just wanted to see if there are any preferences.

**Comment by dlespiau** [comment]
It makes sense to me, yes!

with `footloose` I tried to have the configuration very explicit and not create things without it being declared in the config file. so adding network support would have to be similar.

This can take various forms, but I guess at the minimum we could:
- mandate the network is created/delete outside of jk
- in the machine definition, add a field with the network  name the machine should be attached too

A second form could also be to have the network definition(s) in the footloose config file, but that means having to replicate the options of `docker network create` so seems like work.

What do you think?

**Comment by wintamute** [comment]
It should definitely be explicit, yes, with the default to use the default network as is.

Your minimum approach sounds fine to me.

Having the network name in the footloose config file would be nice, with the option to specify it via argument when creating the config:

`footloose config create --replicas 3 --network my-network`

In any case, what should happen if the network doesn't exist during container creation? You'd get an error from the Docker daemon which should be presented to the user.
Or footloose could create a simple bridge network with the specified name (no other options needed, similar to `docker network create my-network`).

**Comment by dlespiau** [comment]
We could have:

```yaml
cluster:
  name: cluster
  privateKey: cluster-key
machines:
- count: 3
  spec:
    image: quay.io/footloose/centos7
    name: node%d
    network: mynetwork
    portMappings:
    - containerPort: 22
networks:
  - name: mynetwork
```

As you said we could just create a network with the default options and add more later if/when needed.

If a machine tries to connect to a network that doesn't exist, we should error out, not create the network "magically"

**Comment by wintamute** [comment]
Ok, the config looks good to me.
I guess a first approach could be to mandate that specified network has to be created outside manually. Should work for my use case already.

If a network should be created via footloose, you'd need an option in the config file similar to docker-compose I guess (`external=true/false`) and an argument for the config create command.
But I'd start with creating it manually, it's probably enough already unless you need full automation.

**Comment by dlespiau** [comment]
Just so you know, I changed `network` to `networks`, a list of networks to join in https://github.com/weaveworks/footloose/pull/165. Containers can be part of several networks and we need to be able to express that.

**Comment by wintamute** [comment]
OK, great, makes sense, thank you.
