### ISSUE TITLE
Add networks to the show node command

### ISSUE THREAD

**Issue by dlespiau** [weaveworks/footloose#163]
Networks should be part of the output of:

```
footloose status node0 -o json
```

**Comment by najeal** [comment]
Are you talking about `Networks of config file` or `Networks runtime details`?
Networks of config file are already in the `spec` part of the displayed `json`
If you want the Networks runtime details, do you want all fields or specific fields?

**Comment by dlespiau** [comment]
Huuum, I think it'd make sense to add the run-time values and that it'd be a great place to add the IP address there:

```js
"networks": [{
  "name": "xxxx",
  "IPAddress:" "172.17.0.3",
  "IPMask": "255.255.0.0", // (converted from IPPrefixLen"),
  "gateway": "1272.17.0.1",
}]
```
