### ISSUE TITLE
Add an option to select the ignite runtime

### ISSUE THREAD

**Issue by dlespiau** [weaveworks/footloose#213]
`ignite` 0.6.0 has switched the default runtime to `containerd`. This introduces more overhead for users that have to install containerd and often a CNI plugin as well.

We should add a `runtime` config field in the ignite struct to be able to instruct ignite to use the docker runtime.

**Comment by luxas** [comment]
> often a CNI plugin as well

A default CNI plugin is shipped with ignite. Also, we're planning to remove the docker dependency, so I don't see the need for this kind of switch really. The idea is that if you have docker, you have containerd automatically.

**Comment by dlespiau** [comment]
I've just spent 1h with @dimitropoulos because things didn't work out of the box. I suspect this is similar to what this user describes here: https://github.com/weaveworks/ignite/issues/390.

While this may improve soon, a safer option would at the moment seems to be defaulting to the docker runtime in ignite.

**Comment by luxas** [comment]
I'd spend time on making the containerd packaging / preflight checks better than rather than "going back" to docker, but I'm not working on it anymore so you choose.

**Comment by dlespiau** [comment]
I would also do what you are suggesting if I had time to work on it :)

**Comment by dlespiau** [comment]
Related: https://github.com/weaveworks/ignite/pull/408

**Comment by dlespiau** [comment]
Alright, let's have this fixed upstream in ignite then. It has been some time since I opened the issue and things are getting closer to just work™.
