### ISSUE TITLE
Port conflict trouble when separate machines are specified

### ISSUE THREAD

**Issue by cdavisafc** [weaveworks/footloose#232]
Attached are two footloose manifests. 

- One has a single machine specification (including portMappings) and requests 2 machines
- The other has two identical machine specifications (including identical portMappings) and requests 1 of each of these machines (with different base names)

Running `footloose create` with the former succeeds, but with the latter fails reporting ports being unavailable.

Why?

```> footloose create -c footloose_2machines_1machinespec.yaml
INFO[0000] Creating SSH key: cluster-key ...
INFO[0000] Image: quay.io/footloose/centos7:0.6.0 present locally
INFO[0000] Creating machine: firekube-node0 ...
INFO[0001] Creating machine: firekube-node1 ...

> footloose delete -c footloose_2machines_1machinespec.yaml
INFO[0000] Machine firekube-node0 is started, stopping and deleting machine...
INFO[0000] Machine firekube-node1 is started, stopping and deleting machine...

> footloose create -c footloose_2machines_2machinespecs.yaml
INFO[0000] Image: quay.io/footloose/centos7:0.6.0 present locally
INFO[0000] Image: quay.io/footloose/centos7:0.6.0 present locally
INFO[0000] Creating machine: firekube-master0 ...
INFO[0001] Creating machine: firekube-worker0 ...
ERRO[0001] Error response from daemon: driver failed programming external connectivity on endpoint firekube-worker0 (1c9f2625b25f7f7ec2c2f69c1de2e94f50969a9fcf9d159e72b2109c3c212e92): Bind for 0.0.0.0:30443 failed: port is already allocated
ERRO[0001] Error: failed to start containers: firekube-worker0
FATA[0001] exit status 1
```

[footloose_2machines_1machinespec.yaml.txt](https://github.com/weaveworks/footloose/files/4082565/footloose_2machines_1machinespec.yaml.txt)
[footloose_2machines_2machinespecs.yaml.txt](https://github.com/weaveworks/footloose/files/4082566/footloose_2machines_2machinespecs.yaml.txt)

**Comment by chanwit** [comment]
currently, it's been designed like this.
if we create machines from the same spec like `node0` , `node1`, port numbers will be mapped with an increment variable.

while when we have `master0` and `worker0` specs , both start from index 0 but have the similar port mapping spec. so their port mappings collide.

**Comment by chanwit** [comment]
@dlespiau wdyt if this might be a bug?
