### ISSUE TITLE
Make passing option to ssh command more friendly

### ISSUE THREAD

**Issue by dlespiau** [weaveworks/footloose#25]
At the moment, cobra/pflag will bail out if we do something like:

```
$ footloose ssh node0 yum install -y iptables
Error: unknown shorthand flag: 'y' in -y
```

This can be worked around by explicitly stopping option parsing:
```
$ footloose ssh node0 -- yum install -y iptables
```

We could probably do better though? tell cobra/pfag to just leave unknown options alone?

**Comment by Skarlso** [comment]
Hi @dlespiau.

I think this is actually fine... Like, go does the same thing, to cut off option parsing.

For example go list does this:

```
go list -e -json -compiled -test=false -export=false -deps=true -find=false -- f1.go f2.bar
```
Everything is a flag up until -- when there are only patterns or filenames.

That said, you can set this flag: ParseErrorsWhitelist to `true` and it will ignore unknown flags.

However this means that typos in the flags will result in an erratic behaviour. To be honest I like the clear cut between what's going to be an ssh command vs it's still part of the flags to parse. To me this:

```
footloose ssh node0 -- yum install -y iptables
```

... is a helluva lot cleaner than the jumbled version of the second option where flags for the command blend together with flags of footloose.

My 2¢. :)

**Comment by dlespiau** [comment]
Alright, I'm convinced :) let's close this!
