### ISSUE TITLE
Make create and delete idempotent

### ISSUE THREAD

**Issue by dlespiau** [weaveworks/footloose#5]
At the moment, running `create` while the cluster is running will result in an error (because the containers already exist):

```
$ footloose create
INFO[0000] Image: quay.io/footloose/centos7 present locally 
INFO[0000] Creating machine: cluster-node0 ...          
ERRO[0000] docker: Error response from daemon: Conflict. The container name "/cluster-node0" is already in use by container "5134f80b733ecf4561f154c7c43eca2fb5273ae8da0f7c73402b2205ceef1a3e". You have to remove (or rename) that container to be able to reuse that name. 
ERRO[0000] See 'docker run --help'.                     
```
Same with `delete`.

We should make them idempotent.

**Comment by Skarlso** [comment]
Hi @dlespiau. :)

First of all... Love this project!

Second, do you mind if I start to wrap up some of these issues? :) I'll try to learn more while doing them, and then eventually hopefully start adding some stuff that makes sense to you. :)

**Comment by dlespiau** [comment]
Hi!

Thanks for your kind words! Yes, of course, it's fine to look at these issues :) just leave a little note in the issue to say you are working on it so we don't end up doing the same thing twice.
