### ISSUE TITLE
Add it to awesome docker

### ISSUE THREAD

**Issue by veggiemonk** [weaveworks/footloose#58]
Hi @dlespiau,

I really like your project, would you consider adding it yourself to https://github.com/veggiemonk/awesome-docker#development-environment ?

If you have a idea for better suited section, let me know in the PR we can have discussion there with the other team members :D 

Have a great day,

Julien

**Comment by dlespiau** [comment]
Hi Julien!

Thanks for you kind words!

I'd love to have footloose listed on awesome-docker. I'm thinking that the ideal time for me to submit the PR there would be with the next version as it will have support for more OSes than just centos 7 (ie. fedora, ubuntu and amazonlinux). Hopefully that sounds good to you.

**Comment by dlespiau** [comment]
And this is now done! Thanks for the opportunity! Closing.
