### ISSUE TITLE
Ensure a set of basic commands is available on all base images

### ISSUE THREAD

**Issue by dlespiau** [weaveworks/footloose#68]
Container images tend to be quite stripped down, but for container machines, we want a basic set of tools to be available. Defining the exact criteria to decide if a command should be there or not is going to be tricky so we'll have to play it by ear. eg.

- hostname
- ps
- ifconfig/ip
- netstat?
- vi/vim
- ping
- curl
- wget

**Comment by Skarlso** [comment]
curl, wget, nmap... ?

**Comment by dlespiau** [comment]
My vote for curl and wget. nmap seems already a bit too specialised to be part of the base images. Edited the original issue.

**Comment by Skarlso** [comment]
Good point. :) 👍

**Comment by dlespiau** [comment]
Take a look at this!

**Comment by Skarlso** [comment]
👍
