### ISSUE TITLE
Display the cluster status/information

### ISSUE THREAD

**Issue by dlespiau** [weaveworks/footloose#7]
We could show the cluster status and various information about the "machines", maybe.

**Comment by dlespiau** [comment]
@ilmanzo suggested the same thing in #78 .

> to integrate with external tools, it would be very useful to have a 'list' command that outputs all the machine hostnames, and maybe optionally the current host-container port mapping. This can be done with docker but there can be other containers running, we need only the ones created by footloose.

This command is interesting to see the run-time properties of containers, some data is already available in the config file, although showing the "computed" properties like the hostnames is also interesting.

First we need to decide on a name for the command :) `list`, `show`, `status`, `info` are good candidates.

We would go through the machine/containers and for each display properties. A first version could have some basic information:
- hostname
- running?
- list of port mappings
- ...?

It'd be nice if the user could format the output in such a way it's easy to consume by tooling: an option for json output is possible, another is to use go templates similar to `docker inspect --format`.

**Comment by Skarlso** [comment]
Uuuhhh, I'm all for this one if you don't mind.:) I love formatting output.

**Comment by Skarlso** [comment]
@dlespiau ^^

**Comment by dlespiau** [comment]
Of course! It's all yours!

**Comment by dlespiau** [comment]
This was addressed by PR #103. More specific issues are filed to improve on it.
