### ISSUE TITLE
example: footloose + ansible

### ISSUE THREAD

**Issue by dlespiau** [weaveworks/footloose#76]
It'd be nice to have an exemple showing how to set up ansible with footloose machines.

Examples should go in `examples/` and should be linked to from the README.

**Comment by ilmanzo** [comment]
I like this idea! Are you thinking about a specific ansible integration or to simply provide some examples ? e.g. copy files, install packages and so on ?
Another suggestion: how about inserting the ansible playbook to run in the config file, or providing it as a command line option ?

**Comment by dlespiau** [comment]
I wasn't thinking about anything specific no, copying files and installing a package sounds like a perfect example to me!

The issue with inserting the ansible playbook in the config file is that it would tie ansible a bit too closely to ansible :) We can do better with a generic provisioning step though? filed #77 to track it!

**Comment by ilmanzo** [comment]
ok I'll try to come up with some ansible examples

**Comment by dlespiau** [comment]
Thanks! Those examples could then be ported to a provisioning step when we have #77 :) the order in which we those things doesn't really matter /me thinks.
