### ISSUE TITLE
config shouldn't override an existing file

### ISSUE THREAD

**Issue by dlespiau** [weaveworks/footloose#8]
Two more desirable behaviours:

- Error out if a file exists
- "Merge" the existing config file with the option(s) given on the command line

**Comment by dlespiau** [comment]
I now think the first option (erroring out) is the better option. Mutating the configuration is planned through `footloose config set` (#29)

**Comment by Skarlso** [comment]
@dlespiau Hi. Thought I'll pick this one up next, working on 0.3.0 milestone. Is that okay?

**Comment by dlespiau** [comment]
Yup! works for me!
